# Generated by Django 5.1.1 on 2024-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('bot_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('bot_description', models.CharField(default='', max_length=180)),
            ],
        ),
    ]
