# Generated by Django 5.1.2 on 2024-11-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'AGUARDANDO'), (1, 'PREPARANDO'), (2, 'PRONTO')])),
                ('data', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField()),
                ('cliente', models.CharField(default=None, max_length=255)),
                ('produto', models.ManyToManyField(to='produto.produto')),
            ],
        ),
    ]
