# Generated by Django 5.1.2 on 2024-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Aguardando'), (1, 'Preparando'), (2, 'Pronto'), (3, 'Entregue'), (4, 'Cancelado')]),
        ),
    ]
