# Generated by Django 5.1.2 on 2024-11-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_endereco_entrega_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='chat_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
