# Generated by Django 5.1.2 on 2024-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_chat_id_pedido_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='username',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
